CREATE TABLE hoteles(
idhotel NUMBER GENERATED ALWAYS AS IDENTITY,
nombrehotel VARCHAR2(30),
PRIMARY KEY (idhotel)
);

CREATE TABLE paquetes(
idpaquetes NUMBER GENERATED ALWAYS AS IDENTITY,
fecha_inicio varchar2(30),
fecha_final varchar2(30),
lugar NUMBER,
alojamiento NUMBER,
precio NUMBER,
PRIMARY KEY (idpaquetes)
);

CREATE TABLE reservaciones (
 idreservacion NUMBER GENERATED ALWAYS AS IDENTITY,
 idusuario NUMBER,
 preciototal NUMBER,
 idpaqueteviaje NUMBER,
 PRIMARY KEY (idreservacion)
)

CREATE TABLE rols (
 idrol NUMBER,
 puesto_rol varchar2(30),
 PRIMARY KEY (idrol)
)

CREATE TABLE ubicaciones (
 idubicacion NUMBER GENERATED ALWAYS AS IDENTITY,
 nombre_lugar VARCHAR2(20),
 PRIMARY KEY (idubicacion)
) 

CREATE TABLE usuarios (
 idusuario NUMBER GENERATED ALWAYS AS IDENTITY,
 idrol NUMBER,
 nombre_completo VARCHAR2(50),
 nombre_usuario VARCHAR2(20),
 contrasena_usuario VARCHAR2(20),
 telefono NUMBER,
 correo VARCHAR2(20),
 PRIMARY KEY (idusuario)
) 




------------------------- CONSULTA HOTEL -------------------------
CREATE OR REPLACE PROCEDURE CONSULTARHOTEL (P_HOTEL IN NUMBER, C_HOTEL OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_HOTEL FOR
	SELECT nombrehotel FROM ADMIN.HOTELES
	WHERE IDHOTEL = P_HOTEL;
END CONSULTARHOTEL;

------------------------- CONSULTAR HOTELES -------------------------
CREATE OR REPLACE PROCEDURE CONSULTARHOTELES (C_HOTELES OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_HOTELES FOR
	SELECT * FROM HOTELES;
	END CONSULTARHOTELES;

------------------------- ELIMINAR HOTEL -------------------------
CREATE OR REPLACE PROCEDURE ELIMINARHOTEL(P_HOTEL IN NUMBER)
AS
BEGIN
	DELETE FROM ADMIN.HOTELES
	WHERE IDHOTEL = P_HOTEL;
END ELIMINARHOTEL;


------------------------- CARGAR HOTELES -------------------------

CREATE OR REPLACE PROCEDURE CARGARHOTELES (C_HOTELES OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_HOTELES FOR
	SELECT nombrehotel FROM HOTELES;
	END CARGARHOTELES;

------------------------- CARGAR UBICACIONES-------------------------

CREATE OR REPLACE PROCEDURE CARGARUBICACIONES (C_UBICACIONES OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_UBICACIONES FOR
	SELECT nombre_lugar FROM UBICACIONES;
	END CARGARUBICACIONES;

------------------------- CONSULTAR PAQUETE -------------------------

CREATE OR REPLACE PROCEDURE CONSULTARPAQUETE (P_PAQ IN NUMBER, C_PAQUETE OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_PAQUETE FOR
	SELECT * FROM ADMIN.PAQUETES
	WHERE idpaquetes = P_PAQ;
END CONSULTARPAQUETE ;

------------------------- CONSULTAR PAQUETE CON LUGAR -------------------------

CREATE OR REPLACE PROCEDURE CONSULTARPAQUETECONLUGAR (P_PAQ IN NUMBER, C_PAQUETE OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_PAQUETE FOR
	SELECT * FROM ADMIN.PAQUETES
	WHERE LUGAR = P_PAQ;
END CONSULTARPAQUETECONLUGAR;

------------------------- CONSULTAR PAQUETES -------------------------

CREATE OR REPLACE PROCEDURE CONSULTARPAQUETES (C_PAQUETES OUT SYS_REFCURSOR )
AS
BEGIN
	OPEN C_PAQUETES FOR
	SELECT P.idpaquetes, P.FECHA_INICIO,P.FECHA_FINAL, U.NOMBRE_LUGAR,H.NOMBREHOTEL,P.PRECIO FROM PAQUETES P 
	LEFT JOIN ADMIN.UBICACIONES U ON P.LUGAR = U.IDUBICACION
	LEFT JOIN ADMIN.HOTELES H ON P.ALOJAMIENTO = H.IDHOTEL;
END CONSULTARPAQUETES; 



------------------------- VARIANTE ------------------------------------
/*CREATE OR REPLACE PROCEDURE CONSULTARPAQUETES 
(
PAQ_idpaquetes OUT NUMBER, 
PAQ_FECHAINICIO OUT DATE,
PAQ_FECHAFINAL OUT DATE,
PAQ_NOMBRELUGAR OUT VARCHAR2,
PAQ_nombrehotel out VARCHAR2,
PAQ_PRECIO OUT NUMBER)
AS
BEGIN
	SELECT P.IDpaquetes, P.FECHA_INICIO,P.FECHA_FINAL, U.NOMBRE_LUGAR,H.nombrehotel,P.PRECIO INTO PAQ_idpaquetes,PAQ_FECHAINICIO,PAQ_FECHAFINAL,PAQ_NOMBRELUGAR,PAQ_nombrehotel,PAQ_PRECIO FROM PAQUETES P 
	LEFT JOIN ADMIN.UBICACIONES U ON P.LUGAR = U.IDUBICACION
	LEFT JOIN ADMIN.HOTELES H ON P.ALOJAMIENTO = H.IDHOTEL;
    RETURN;
END CONSULTARPAQUETES; 
*/

------------------------- CONSULTAR UBICACION -------------------------

CREATE OR REPLACE PROCEDURE CONSULTARUBICACION (P_UBI IN NUMBER, C_UBICACION OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_UBICACION FOR
	SELECT * FROM ADMIN.UBICACIONES
	WHERE IDUBICACION = P_UBI;
END CONSULTARUBICACION;

------------------------- CONSULTAR UBICACIONES -------------------------
CREATE OR REPLACE PROCEDURE CONSULTARUBICACIONES (C_UBICACIONES OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_UBICACIONES FOR
	SELECT * FROM UBICACIONES;
END CONSULTARUBICACIONES;

------------------------- CONSULTAR UBICACIONES DROPDOWN -------------------------
CREATE OR REPLACE PROCEDURE CONSULTARUBICACIONESDROPDOOWN (C_UBICACIONES OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_UBICACIONES FOR
	SELECT * FROM UBICACIONES;
END CONSULTARUBICACIONESDROPDOOWN;

------------------------- CONSULTAR USUARIOS-------------------------
CREATE OR REPLACE PROCEDURE CONSULTARUSUARIOS (C_USUARIOS OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_USUARIOS FOR
	SELECT * FROM USUARIOS;
END CONSULTARUSUARIOS;

------------------------- CREAR USUARIOS-------------------------
CREATE OR REPLACE PROCEDURE CREARUSUARIOS (P_IDROL IN NUMBER,P_NAME IN VARCHAR2,P_USERNAME IN VARCHAR2, P_PASS IN VARCHAR2, P_PHONE IN NUMBER, P_MAIL IN VARCHAR2)
AS
BEGIN
	INSERT INTO USUARIOS (IDROL,NOMBRE_COMPLETO,NOMBRE_USUARIO, CONTRASENA_USUARIO,  TELEFONO, CORREO) VALUES (P_IDROL,P_NAME,P_USERNAME, P_PASS, P_PHONE, P_MAIL );
END CREARUSUARIOS;



Select * from usuarios;

------------------------- ELIMINAR PAQUETE-------------------------
CREATE OR REPLACE PROCEDURE ELIMINARPAQUETE(P_PAQUETE IN NUMBER)
AS
BEGIN
	DELETE FROM PAQUETES
	WHERE IDPAQUETES = P_PAQUETE;
END ELIMINARPAQUETE;

------------------------- ELIMINAR UBICACION-------------------------
CREATE OR REPLACE PROCEDURE ELIMINARUBICACION(P_UBICACION IN NUMBER)
AS
BEGIN
	DELETE FROM ADMIN.UBICACIONES
	WHERE IDUBICACION = P_UBICACION;
END ELIMINARUBICACION;

------------------------- ELIMINAR USUARIO-------------------------
CREATE OR REPLACE PROCEDURE ELIMINARUSUARIO(P_USUARIO IN NUMBER)
AS
BEGIN
	DELETE FROM ADMIN.USUARIOS
	WHERE IDUSUARIO = P_USUARIO;
END ELIMINARUSUARIO;

------------------------- HACER ADMIN-------------------------
CREATE OR REPLACE PROCEDURE HACERADMIN(P_USUARIO IN NUMBER)
AS
BEGIN
	UPDATE ADMIN.USUARIOS SET IDROL=999
	WHERE IDUSUARIO = P_USUARIO;
END HACERADMIN;

------------------------- INSERTAR HOTEL-------------------------
CREATE OR REPLACE PROCEDURE INSERTARHOTEL(P_NAME IN VARCHAR2)
AS
BEGIN
	INSERT INTO HOTELES (NOMBREHOTEL) VALUES (P_NAME);
END INSERTARHOTEL;

------------------------- INSERTAR PAQUETES-------------------------
CREATE OR REPLACE PROCEDURE INSERTARPAQUETES( P_FINICIO IN VARCHAR2, P_FFINAL IN VARCHAR2, P_LUGAR IN NUMBER, P_ALOJAM IN NUMBER, P_PRECIO IN NUMBER)
AS
BEGIN
	INSERT INTO PAQUETES ( FECHA_INICIO, FECHA_FINAL, LUGAR,ALOJAMIENTO, PRECIO) VALUES ( P_FINICIO, P_FFINAL, P_LUGAR,P_ALOJAM, P_PRECIO);
END INSERTARPAQUETES;


------------------------- INSERTAR UBICACION -------------------------
CREATE OR REPLACE PROCEDURE INSERTARUBICACION (P_LUGAR IN VARCHAR2)
AS
BEGIN
	INSERT INTO UBICACIONES (NOMBRE_LUGAR) VALUES (P_LUGAR);
END INSERTARUBICACION;

------------------------- LLENAR COMBO UBICACIONES -------------------------
CREATE OR REPLACE PROCEDURE LLENARCOMBOUBICACIONES(C_UBICACIONES OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_UBICACIONES FOR
	SELECT * FROM UBICACIONES;
END LLENARCOMBOUBICACIONES;

------------------------- MODIFICAR HOTEL -------------------------
CREATE OR REPLACE PROCEDURE MODIFICARHOTEL(P_ID IN NUMBER, P_NAME IN VARCHAR2)
AS
BEGIN
	UPDATE ADMIN.HOTELES SET NOMBREHOTEL = P_NAME
	WHERE IDHOTEL = P_ID;
END MODIFICARHOTEL;

------------------------- MODIFICAR PAQUETE -------------------------
CREATE OR REPLACE PROCEDURE MODIFICARPAQUETE(P_ALOJAM IN NUMBER, P_FINICIO IN DATE, P_FFINAL IN DATE, P_LUGAR IN NUMBER, P_PRECIO IN NUMBER, P_ID IN NUMBER)
AS
BEGIN
	UPDATE ADMIN.PAQUETES SET ALOJAMIENTO = P_ALOJAM,FECHA_INICIO = P_FINICIO, FECHA_FINAL = P_FFINAL, LUGAR = P_LUGAR, PRECIO = P_PRECIO
	WHERE IDPAQUETES = P_ID;
END MODIFICARPAQUETE;

------------------------- MODIFICAR UBICACION -------------------------
CREATE OR REPLACE PROCEDURE MODIFICARUBICACION(P_ID IN NUMBER, P_NAME IN VARCHAR2)
AS
BEGIN
	UPDATE ADMIN.UBICACIONES SET NOMBRE_LUGAR = P_NAME
	WHERE IDUBICACION = P_ID;
END MODIFICARUBICACION;

------------------------- QUITAR ADMIN-------------------------
CREATE OR REPLACE PROCEDURE QUITARADMIN(P_USUARIO IN NUMBER)
AS
BEGIN
	UPDATE ADMIN.USUARIOS SET IDROL=0
	WHERE IDUSUARIO = P_USUARIO;
END QUITARADMIN;

------------------------- VALIDAR USUARIO -------------------------
CREATE OR REPLACE PROCEDURE VALIDARUSUARIO(P_USER IN VARCHAR2, P_PASS IN VARCHAR2, C_USUARIOS OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_USUARIOS FOR
	SELECT * FROM USUARIOS
	WHERE NOMBRE_USUARIO = P_USER AND contrasena_usuario = P_PASS; 
END VALIDARUSUARIO;

------------------------- LLENAR COMBO ALOJAMIENTOS-------------------------
CREATE OR REPLACE PROCEDURE LLENARCOMBOUALOJAMIENTOS(C_ALOJAMIENTOS OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN C_ALOJAMIENTOS FOR
	SELECT * FROM HOTELES;
END LLENARCOMBOUALOJAMIENTOS;

------------------------- RESERVAR PAQUETE-------------------------
CREATE OR REPLACE PROCEDURE RESERVARPAQUETE(P_PAQID IN NUMBER, P_IDUSER IN NUMBER, P_PRETO IN NUMBER)
AS
BEGIN
	INSERT INTO RESERVACIONES (IDPAQUETEVIAJE, IDUSUARIO, PRECIOTOTAL) VALUES (P_PAQID, P_IDUSER, P_PRETO);
END RESERVARPAQUETE;





----
-------------------TRIGGER 
----
CREATE OR REPLACE TRIGGER TRG_Reservacion
  AFTER INSERT ON reservaciones
  
DECLARE   
  VAR_id_reservacion VARCHAR2(20); 
  VAR_precio NUMBER(20); 
BEGIN
    SELECT idreservacion, preciototal INTO VAR_id_reservacion, VAR_precio  FROM reservaciones;
    IF INSERTING THEN
      INSERT INTO Auditoria_reservaciones_insert(id_reservacion,precio,fechaInsert) VALUES ( VAR_id_reservacion,VAR_precio, SYSDATE);
    END IF;
END;
------

CREATE TABLE Auditoria_reservaciones_insert(

  id_auditoria NUMBER GENERATED ALWAYS AS IDENTITY,
  id_reservacion NUMBER(10),
  precio NUMBER(10),
  fechaInsert Date,
  PRIMARY KEY (id_auditoria)
);


INSERT INTO hoteles ( NOMBREHOTEL) VALUES( 'Radisson');
INSERT INTO hoteles ( NOMBREHOTEL) VALUES( 'Hollywood');
INSERT INTO hoteles ( NOMBREHOTEL) VALUES( 'Western Jaco');
INSERT INTO hoteles ( NOMBREHOTEL) VALUES( 'PruebaHotel');
INSERT INTO hoteles ( NOMBREHOTEL) VALUES( 'PruebaHotel');

INSERT INTO paquetes ( FECHA_INICIO, FECHA_FINAL, lugar, alojamiento,precio) VALUES
( '2022-04-28', '2022-05-06', 1, 2, 300);



INSERT INTO rols (IDROL, PUESTO_ROL) VALUES(0, 'CLIENTE');
INSERT INTO rols (IDROL, PUESTO_ROL) VALUES(999, 'ADMIN');



INSERT INTO ubicaciones ( NOMBRE_LUGAR) VALUES( 'Tamarindo');
INSERT INTO ubicaciones ( NOMBRE_LUGAR) VALUES( 'Santa Teresa');
INSERT INTO ubicaciones ( NOMBRE_LUGAR) VALUES( 'Turrialba');
INSERT INTO ubicaciones ( NOMBRE_LUGAR) VALUES( 'rere');
INSERT INTO ubicaciones ( NOMBRE_LUGAR) VALUES( 'prueba2');



INSERT INTO usuarios ( IDROL, NOMBRE_COMPLETO, NOMBRE_USUARIO, CONTRASENA_USUARIO, TELEFONO, CORREO) VALUES( 999, 'JOSE PABLO RODRIGUEZ', 'admin', 'admin', 85433212, 'soyadmin@gmail.com');
INSERT INTO usuarios (IDROL, NOMBRE_COMPLETO, NOMBRE_USUARIO, CONTRASENA_USUARIO, TELEFONO, CORREO) VALUES( 0, 'MARIA FLORES', 'maria987', 'm12345', 82457643, 'marflores@gmail.com');
INSERT INTO usuarios ( IDROL, NOMBRE_COMPLETO, NOMBRE_USUARIO, CONTRASENA_USUARIO, TELEFONO, CORREO) VALUES( 0, 'ANDRES GARCIA', 'andres987', 'a12345', 86426643, 'andgar@gmail.com');